version: "3.9"

services:
  redis_db:
    image: "redis:alpine"
    restart: always
    ports:
      - 6379:6379
    container_name: redis-db
    command: redis-server
    volumes:
      - ./redis-data:/data
