version: "3.9"

x-logging: &default-logging
  options:
    max-size: "10m"
    max-file: "10"
  driver: json-file

services:
  redis-db:
    extends:
      file: ./services/redis.yml
      service: redis-db
    logging: *default-logging

  db-init:
    extends:
      file: ./services/db.yml
      service: db-init

  db:
    depends_on:
      db-init:
        condition: service_completed_successfully
    extends:
      file: ./services/db.yml
      service: db
    logging: *default-logging

  blockscout:
    depends_on:
      - db
      - redis-db
    build:
      context: ..
      dockerfile: ./docker/oldUI.Dockerfile
      args:
        RELEASE_VERSION: 6.10.0
    logging: *default-logging
    restart: always
    stop_grace_period: 5m
    container_name: "blockscout"
    links:
      - db:database
    command: sh -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - ./envs/common-blockscout.env
    ports:
      - 4000:4000
    volumes:
      - ./logs/:/app/logs/

  visualizer:
    extends:
      file: ./services/visualizer.yml
      service: visualizer
    logging: *default-logging

  sig-provider:
    extends:
      file: ./services/sig-provider.yml
      service: sig-provider
    logging: *default-logging

  stats-db-init:
    extends:
      file: ./services/stats.yml
      service: stats-db-init

  stats-db:
    depends_on:
      stats-db-init:
        condition: service_completed_successfully
    extends:
      file: ./services/stats.yml
      service: stats-db

  stats:
    depends_on:
      - stats-db
      - blockscout
    extends:
      file: ./services/stats.yml
      service: stats
