version: "3.9"

x-logging: &default-logging
  options:
    max-size: "10m"
    max-file: "10"
  driver: json-file

services:
  redis-db:
    extends:
      file: ./services/redis.yml
      service: redis-db
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    environment:
      - BLOCKSCOUT_LOG_LEVEL=debug

  db-init:
    extends:
      file: ./services/db.yml
      service: db-init

  db:
    depends_on:
      db-init:
        condition: service_completed_successfully
    extends:
      file: ./services/db.yml
      service: db
    logging: *default-logging

  blockscout:
    depends_on:
      - db
      - redis-db
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        CACHE_EXCHANGE_RATES_PERIOD: ""
        API_V1_READ_METHODS_DISABLED: "false"
        DISABLE_WEBAPP: "false"
        API_V1_WRITE_METHODS_DISABLED: "false"
        CACHE_TOTAL_GAS_USAGE_COUNTER_ENABLED: ""
        CACHE_ADDRESS_WITH_BALANCES_UPDATE_INTERVAL: ""
        ADMIN_PANEL_ENABLED: ""
        RELEASE_VERSION: 6.2.2
    logging: *default-logging
    restart: always
    stop_grace_period: 5m
    container_name: "blockscout"
    links:
      - db:database
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - ./envs/common-blockscout.env
    ports:
      - 4000:4000
    volumes:
      - ./logs/:/app/logs/
    environment:
      - BLOCKSCOUT_LOG_LEVEL=debug
      - BLOCKSCOUT_TRANSACTION_DECODER_LOG=/app/logs/transaction_decoder.log
    command: >
      sh -c "
        bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" &&
        bin/blockscout start &
        sleep 60 &&
        tail -f /app/logs/transaction_decoder.log | grep -C 10 'Failed to decode' > /app/logs/failed_decodes.txt
      "

  visualizer:
    extends:
      file: ./services/visualizer.yml
      service: visualizer
    logging: *default-logging

  sig-provider:
    extends:
      file: ./services/sig-provider.yml
      service: sig-provider
    logging: *default-logging

  stats-db-init:
    extends:
      file: ./services/stats.yml
      service: stats-db-init

  stats-db:
    depends_on:
      stats-db-init:
        condition: service_completed_successfully
    extends:
      file: ./services/stats.yml
      service: stats-db

  stats:
    depends_on:
      - stats-db
      - blockscout
    extends:
      file: ./services/stats.yml
      service: stats
