version: "3.9"

x-logging: &default-logging
  options:
    max-size: "10m"
    max-file: "10"
  driver: json-file

services:
  redis-db:
    extends:
      file: ./services/redis.yml
      service: redis-db
    logging: *default-logging

  db-init:
    extends:
      file: ./services/db.yml
      service: db-init

  db:
    depends_on:
      db-init:
        condition: service_completed_successfully
    extends:
      file: ./services/db.yml
      service: db
    logging: *default-logging

  backend:
    depends_on:
      - db
      - redis-db
    extends:
      file: ./services/backend.yml
      service: backend
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        CACHE_EXCHANGE_RATES_PERIOD: ""
        API_V1_READ_METHODS_DISABLED: "false"
        DISABLE_WEBAPP: "false"
        API_V1_WRITE_METHODS_DISABLED: "false"
        CACHE_TOTAL_GAS_USAGE_COUNTER_ENABLED: ""
        CACHE_ADDRESS_WITH_BALANCES_UPDATE_INTERVAL: ""
        ADMIN_PANEL_ENABLED: ""
        RELEASE_VERSION: 6.2.2
    logging: *default-logging
    restart: always
    stop_grace_period: 5m
    container_name: "blockscout"
    links:
      - db:database
    environment:
      ETHEREUM_JSONRPC_HTTP_URL: https://mainnetrpc.num.network/explorer/
      ETHEREUM_JSONRPC_TRACE_URL: https://mainnetrpc.num.network/explorer/
      ETHEREUM_JSONRPC_WS_URL: wss://mainnetrpc.num.network/ws/
      CHAIN_ID: "10507"
    volumes:
      - ./logs/:/app/logs/

  visualizer:
    extends:
      file: ./services/visualizer.yml
      service: visualizer
    logging: *default-logging

  sig-provider:
    extends:
      file: ./services/sig-provider.yml
      service: sig-provider
    logging: *default-logging

  frontend:
    depends_on:
      - backend
    extends:
      file: ./services/frontend.yml
      service: frontend

  stats-db-init:
    extends:
      file: ./services/stats.yml
      service: stats-db-init

  stats-db:
    depends_on:
      stats-db-init:
        condition: service_completed_successfully
    extends:
      file: ./services/stats.yml
      service: stats-db

  stats:
    depends_on:
      - stats-db
      - backend
    extends:
      file: ./services/stats.yml
      service: stats

  proxy:
    depends_on:
      - backend
      - frontend
      - stats
    extends:
      file: ./services/nginx.yml
      service: proxy
